AWSTemplateFormatVersion: "2010-09-09"
Description: Add Inbound Rule to Existing Security Group

Parameters:
  SecurityGroupId:
    Type: Ssg-045fc1df40f9a85c8
    Description: ID of the existing Security Group
    # Enter the ID of your existing Security Group

  SourceCidrIp:
    Type: 0.0.0.0/0
    Description: Source IP range for the inbound rule
    # Enter the desired source IP range (e.g., 0.0.0.0/0 for all)

Resources:
  InboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroupId
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: !Ref SourceCidrIp

