AWSTemplateFormatVersion: '2010-09-09'
Description: Add inbound rule to allow 3306 from 10.125.0.0/16 to an existing security group

Resources:
  SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: sg-0e17d8625e5d5d6f1
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      CidrIp: 10.125.0.0/16